# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


gem "rspec", "~> 3.6"
gem "capybara", "~> 2.15"

# Added at 2017-10-11 21:36:05 -0600 by Rob:
gem "chromedriver-helper", "~> 1.1"

# Added at 2017-10-11 21:37:18 -0600 by Rob:
gem "selenium-webdriver", "~> 3.6"

# Added at 2017-10-12 20:51:52 -0600 by Rob:
gem "httparty", "~> 0.15.6"
